spring:
  datasource:
    # Use environment variable with fallback
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5433/${POSTGRES_DEV_DB}}
    username: ${POSTGRES_DEV_USER}
    password: ${POSTGRES_DEV_PASSWORD}
  jpa:
    show-sql: true
    open-in-view: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        generate_statistics: true

    # Redis configuration
    redis:
      host: localhost
      port: 6380
      password: ${REDIS_PASSWORD}
      timeout: 2000

  # MongoDB configuration
  data:
    mongodb:
      uri: mongodb://${MONGO_ROOT_USERNAME}:${MONGO_ROOT_PASSWORD}@localhost:27017/${MONGO_DATABASE}?authSource=admin


  flyway:
    user: ${POSTGRES_DEV_USER}
    password: ${POSTGRES_DEV_PASSWORD}
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 0
    #clean-disabled: false  # Allow database cleanup in test environment

server:
  port: 8082