CREATE SEQUENCE IF NOT EXISTS appointments_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS colleges_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS courses_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS degrees_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS explainers_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS students_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS availability_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS reviews_id_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS appointments
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    expected_end_time TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    start_time        TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    explainer_id      BIGINT,
    student_id        BIGINT,
    CONSTRAINT appointments_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS  colleges
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255)                            NOT NULL,
    CONSTRAINT colleges_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS  courses
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name      VARCHAR(255)                            NOT NULL,
    degree_id BIGINT,
    CONSTRAINT courses_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS  degrees
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       VARCHAR(255)                            NOT NULL,
    college_id BIGINT,
    CONSTRAINT degrees_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS  explainer_courses
(
    explainer_id BIGINT NOT NULL,
    course_id    BIGINT NOT NULL,
    CONSTRAINT explainer_courses_pkey PRIMARY KEY (explainer_id, course_id)
);

CREATE TABLE IF NOT EXISTS explainers
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email    VARCHAR(255)                            NOT NULL,
    language VARCHAR(255),
    name     VARCHAR(255),
    CONSTRAINT explainers_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS  students
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email VARCHAR(255)                            NOT NULL,
    name  VARCHAR(255)                            NOT NULL,
    CONSTRAINT students_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS  availabilities
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    day_of_week  VARCHAR(255)                            NOT NULL,
    start        time WITHOUT TIME ZONE                  NOT NULL,
    "end"        time WITHOUT TIME ZONE                  NOT NULL,
    explainer_id BIGINT,
    CONSTRAINT pk_availabilities PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS reviews
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    rating         INTEGER      NOT NULL,
    comment        VARCHAR(500) NOT NULL,
    appointment_id BIGINT       NOT NULL,
    student_id     BIGINT       NOT NULL,
    explainer_id   BIGINT       NOT NULL,
    created_at     TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at     TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_reviews PRIMARY KEY (id)
);


ALTER TABLE availabilities
    ADD CONSTRAINT FK_AVAILABILITIES_ON_EXPLAINER FOREIGN KEY (explainer_id) REFERENCES explainers (id);

ALTER TABLE students
    ADD CONSTRAINT uke2rndfrsx22acpq2ty1caeuyw UNIQUE (email);

ALTER TABLE explainers
    ADD CONSTRAINT ukpxcsl6v7ma7ioyvumls1mi682 UNIQUE (email);

ALTER TABLE courses
    ADD CONSTRAINT fk1q2jh9x42qm5dspcsc6ux6rfe FOREIGN KEY (degree_id) REFERENCES degrees (id) ON DELETE NO ACTION;

ALTER TABLE degrees
    ADD CONSTRAINT fk33qjwkxh3jxe2psatngi0wqxt FOREIGN KEY (college_id) REFERENCES colleges (id) ON DELETE NO ACTION;

ALTER TABLE appointments
    ADD CONSTRAINT fk4ciselyhy10ku6eiyabq3ylga FOREIGN KEY (student_id) REFERENCES students (id) ON DELETE NO ACTION;

ALTER TABLE appointments
    ADD CONSTRAINT fk6h9p83fo77rpm08mihp8h8uj5 FOREIGN KEY (explainer_id) REFERENCES explainers (id) ON DELETE NO ACTION;

ALTER TABLE explainer_courses
    ADD CONSTRAINT fkf9llo8a49bgphb5yp4yyho6qg FOREIGN KEY (course_id) REFERENCES courses (id) ON DELETE NO ACTION;

ALTER TABLE explainer_courses
    ADD CONSTRAINT fknutx4lxhsrqkgl20j6njnjntn FOREIGN KEY (explainer_id) REFERENCES explainers (id) ON DELETE NO ACTION;

ALTER TABLE reviews
    ADD CONSTRAINT FK_REVIEWS_ON_APPOINTMENT FOREIGN KEY (appointment_id) REFERENCES appointments (id);

ALTER TABLE reviews
    ADD CONSTRAINT FK_REVIEWS_ON_EXPLAINER FOREIGN KEY (explainer_id) REFERENCES explainers (id);

ALTER TABLE reviews
    ADD CONSTRAINT FK_REVIEWS_ON_STUDENT FOREIGN KEY (student_id) REFERENCES students (id);