-- V2__add_audit_fields_and_organization.sql
-- Migration to add audit fields and multi-tenancy support

-- Add audit fields and deleted_at to existing tables
ALTER TABLE students ADD COLUMN created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE students ADD COLUMN updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE students ADD COLUMN deleted_at TIMESTAMP WITHOUT TIME ZONE;
ALTER TABLE students ADD COLUMN organization_id BIGINT NOT NULL DEFAULT 1;
ALTER TABLE students ADD COLUMN role VARCHAR(50) NOT NULL DEFAULT 'STUDENT';

ALTER TABLE explainers ADD COLUMN created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE explainers ADD COLUMN updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE explainers ADD COLUMN deleted_at TIMESTAMP WITHOUT TIME ZONE;
ALTER TABLE explainers ADD COLUMN organization_id BIGINT NOT NULL DEFAULT 1;
ALTER TABLE explainers ADD COLUMN role VARCHAR(50) NOT NULL DEFAULT 'EXPLAINER';

ALTER TABLE appointments ADD COLUMN created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE appointments ADD COLUMN updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE appointments ADD COLUMN deleted_at TIMESTAMP WITHOUT TIME ZONE;
ALTER TABLE appointments ADD COLUMN course_id BIGINT;
ALTER TABLE appointments ADD COLUMN status VARCHAR(50) NOT NULL DEFAULT 'SCHEDULED';

ALTER TABLE courses ADD COLUMN created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE courses ADD COLUMN updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE courses ADD COLUMN deleted_at TIMESTAMP WITHOUT TIME ZONE;

ALTER TABLE degrees ADD COLUMN created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE degrees ADD COLUMN updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE degrees ADD COLUMN deleted_at TIMESTAMP WITHOUT TIME ZONE;

ALTER TABLE colleges ADD COLUMN created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE colleges ADD COLUMN updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE colleges ADD COLUMN deleted_at TIMESTAMP WITHOUT TIME ZONE;
ALTER TABLE colleges ADD COLUMN organization_id BIGINT NOT NULL DEFAULT 1;

ALTER TABLE availabilities ADD COLUMN created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE availabilities ADD COLUMN updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE availabilities ADD COLUMN deleted_at TIMESTAMP WITHOUT TIME ZONE;

ALTER TABLE reviews ADD COLUMN deleted_at TIMESTAMP WITHOUT TIME ZONE;

-- Create organizations table (multi-tenancy support)
CREATE TABLE IF NOT EXISTS organizations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255) NOT NULL UNIQUE,
    email VARCHAR(255) NOT NULL UNIQUE,
    description VARCHAR(500),
    active BOOLEAN NOT NULL DEFAULT true,
    tenant_id VARCHAR(100) NOT NULL UNIQUE,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    deleted_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_organizations PRIMARY KEY (id)
);

-- Add foreign key constraints for organization_id
ALTER TABLE colleges ADD CONSTRAINT fk_colleges_on_organization FOREIGN KEY (organization_id) REFERENCES organizations (id);
ALTER TABLE students ADD CONSTRAINT fk_students_on_organization FOREIGN KEY (organization_id) REFERENCES organizations (id);
ALTER TABLE explainers ADD CONSTRAINT fk_explainers_on_organization FOREIGN KEY (organization_id) REFERENCES organizations (id);

-- Add course_id foreign key to appointments
ALTER TABLE appointments ADD CONSTRAINT fk_appointments_on_course FOREIGN KEY (course_id) REFERENCES courses (id);

-- Create indexes for common queries
CREATE INDEX idx_students_organization_id ON students(organization_id);
CREATE INDEX idx_explainers_organization_id ON explainers(organization_id);
CREATE INDEX idx_colleges_organization_id ON colleges(organization_id);
CREATE INDEX idx_students_deleted_at ON students(deleted_at);
CREATE INDEX idx_explainers_deleted_at ON explainers(deleted_at);
CREATE INDEX idx_appointments_deleted_at ON appointments(deleted_at);
CREATE INDEX idx_organizations_tenant_id ON organizations(tenant_id);
CREATE INDEX idx_organizations_active ON organizations(active);

