name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Set up Maven settings
        run: |
          mkdir -p $HOME/.m2
          echo "<settings><interactiveMode>false</interactiveMode></settings>" > $HOME/.m2/settings.xml

      - name: Build with Maven
        run: mvn -B clean verify

      - name: Upload Surefire test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports
          path: target/surefire-reports/

      - name: Upload JaCoCo coverage report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: target/site/jacoco/

      - name: Package application
        run: mvn -B package

      # Uncomment and configure the following steps if you want to build and push a Docker image
      # - name: Log in to DockerHub
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}

      # - name: Build Docker image
      #   run: docker build -t your-dockerhub-username/your-app-name:${{ github.sha }} .

      # - name: Push Docker image
      #   run: docker push your-dockerhub-username/your-app-name:${{ github.sha }}

  # Optional: Add a deployment job here if you want to deploy after build
  # deploy:
  #   needs: build-test
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Deploy to production server
  #       run: echo "Deploy step goes here"